waiting:
  - message: I did this someday
    image: cool.gif
    date: Monday, 7pm
    status: waiting
  - message: What the hell is this
    image: crazy-jump.gif
    date: Monday, 8pm
    status: waiting
  - message: Prototyping a sword
    image: sword-test.gif
    date: Monday, 9pm
    status: waiting
done: 
